/** Shared interest catalog + seed content for personalized feed */

const INTERESTS = [
  { id: 'technology', label: 'Technology', emoji: '💻' },
  { id: 'sports', label: 'Sports', emoji: '⚽' },
  { id: 'music', label: 'Music', emoji: '🎵' },
  { id: 'movies', label: 'Movies & TV', emoji: '🎬' },
  { id: 'gaming', label: 'Gaming', emoji: '🎮' },
  { id: 'fashion', label: 'Fashion', emoji: '👗' },
  { id: 'food', label: 'Food', emoji: '🍕' },
  { id: 'travel', label: 'Travel', emoji: '✈️' },
  { id: 'fitness', label: 'Fitness', emoji: '💪' },
  { id: 'art', label: 'Art & Design', emoji: '🎨' },
  { id: 'business', label: 'Business', emoji: '💼' },
  { id: 'science', label: 'Science', emoji: '🔬' },
  { id: 'education', label: 'Education', emoji: '📚' },
  { id: 'photography', label: 'Photography', emoji: '📷' },
  { id: 'news', label: 'News', emoji: '📰' },
  { id: 'comedy', label: 'Comedy', emoji: '😂' }
];

const VALID_INTEREST_IDS = new Set(INTERESTS.map(i => i.id));

const GENDERS = [
  { id: 'female', label: 'Female' },
  { id: 'male', label: 'Male' },
  { id: 'non-binary', label: 'Non-binary' },
  { id: 'prefer-not-to-say', label: 'Prefer not to say' }
];

/** Seed creator profiles (one per interest) */
const CREATORS = INTERESTS.map((interest) => ({
  email: `creator.${interest.id}@nexora.seed`,
  name: `${interest.label} Hub`,
  bio: `Daily ${interest.label.toLowerCase()} updates and community picks on Nexora.`,
  interest: interest.id,
  avatar: ''
}));

/** Sample posts per interest (autogenerated feed) */
const SEED_POSTS = {
  technology: [
    'Hot take: learning TypeScript is still one of the best career investments in 2026 💻',
    'What stack are you shipping with this month? Drop it below 👇',
    'AI tools are changing how we build — but fundamentals still win. Agree?'
  ],
  sports: [
    'That final minute comeback energy 🔥 Who is your team of the season?',
    'Morning run done. Consistency > intensity. Who is training today?',
    'Best sports documentary you have watched recently?'
  ],
  music: [
    'Song stuck in your head right now? Share the title 🎵',
    'New playlist drop: chill focus beats for deep work.',
    'Live concerts hit different. Last show you went to?'
  ],
  movies: [
    'Underrated series everyone should watch this weekend 🎬',
    'Cinema or streaming? The debate continues…',
    'One movie that changed how you see storytelling?'
  ],
  gaming: [
    'What are you grinding this week? Ranked or story mode? 🎮',
    'Co-op recommendations needed — drop your favorites!',
    'Controller vs keyboard: choose your fighter.'
  ],
  fashion: [
    'Outfit of the day energy ✨ What are you wearing today?',
    'Thrift finds > fast fashion. Agree or disagree?',
    'One staple piece every wardrobe needs…'
  ],
  food: [
    'Comfort food of the day? We are hungry already 🍕',
    'Home cook tip: salt early, taste often.',
    'Best street food in your city — go!'
  ],
  travel: [
    'Dream destination for 2026? ✈️',
    'Travel light challenge: what would you pack for 7 days?',
    'Hidden gem places > tourist traps. Share yours.'
  ],
  fitness: [
    'No zero days. Even 15 minutes counts 💪',
    'Protein goal check-in — how are you doing?',
    'Rest days are part of the plan. Who needs that reminder?'
  ],
  art: [
    'Show us your latest sketch, photo edit, or design 🎨',
    'Color palette of the week: warm neutrals + one bold accent.',
    'Art block tip: copy masters, then break the rules.'
  ],
  business: [
    'Small win today in your business or side hustle? 💼',
    'Networking is just helping people at scale.',
    'What metric are you watching this quarter?'
  ],
  science: [
    'Cool science fact that blew your mind recently? 🔬',
    'Space, climate, biotech — which frontier excites you most?',
    'Curiosity is a superpower. What are you learning?'
  ],
  education: [
    'Learning in public > learning alone. What are you studying? 📚',
    'Best free resource you have found this year?',
    'Pomodoro or deep blocks — how do you study?'
  ],
  photography: [
    'Golden hour never misses 📷 Share your favorite shot tip.',
    'Phone cameras are insane now. Filter or natural?',
    'Composition tip: leave breathing room around the subject.'
  ],
  news: [
    'One headline that actually matters this week 📰',
    'How do you stay informed without the doomscroll?',
    'Local news needs more love. What is happening near you?'
  ],
  comedy: [
    'If your day was a meme, which one? 😂',
    'Dad jokes only in the comments. We will allow it.',
    'Comedy heals. Share a clean joke that always works.'
  ]
};

function normalizeInterests(list = []) {
  return [...new Set(
    (list || [])
      .map(i => String(i).toLowerCase().trim())
      .filter(i => VALID_INTEREST_IDS.has(i))
  )];
}

module.exports = {
  INTERESTS,
  VALID_INTEREST_IDS,
  GENDERS,
  CREATORS,
  SEED_POSTS,
  normalizeInterests
};
